--- #YAML:1.0
name:               Net-FTP-Robust
version:            0.02
abstract:           download files over FTP
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Report:  0.25
    Test::Pod:    1.00
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
